# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gituser < Formula
  desc ""
  homepage "https://github.com/lucasnevespereira/homebrew-tools"
  version "1.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lucasnevespereira/go-gituser/releases/download/v1.3.2/gituser_1.3.2_Darwin_x86_64.tar.gz"
      sha256 "fc6c752fc2f4a3265a8fb3a00eee7110b6c032155aa618861d13fb61e314478b"

      def install
        bin.install "gituser"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lucasnevespereira/go-gituser/releases/download/v1.3.2/gituser_1.3.2_Darwin_arm64.tar.gz"
      sha256 "0924dab917c2039dcfef116c201bbb63829c05563c72b5920164d6cd9bfac494"

      def install
        bin.install "gituser"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucasnevespereira/go-gituser/releases/download/v1.3.2/gituser_1.3.2_Linux_arm64.tar.gz"
      sha256 "968dd9a7b6a520b1fea89a6bb5694458ed55aa3fa2478ff10b31cd5ee71637e4"

      def install
        bin.install "gituser"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucasnevespereira/go-gituser/releases/download/v1.3.2/gituser_1.3.2_Linux_x86_64.tar.gz"
      sha256 "24e1a38dd36e161035e40676ef4318f3f51d39e965748353b6d5417797f017ab"

      def install
        bin.install "gituser"
      end
    end
  end
end
