# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gituser < Formula
  desc ""
  homepage "https://github.com/lucasnevespereira/homebrew-tools"
  version "v1.5.0"
  disable! date: "2025-07-25", because: "the cask should be used now instead", replacement_cask: "gituser"

  on_macos do
    url "https://github.com/lucasnevespereira/go-gituser/releases/download/vv1.5.0/gituser_v1.5.0_darwin_all.tar.gz"
    sha256 "f6220126614d1ddeb717eef6b81fe7ceea21f37523bde0f56945f96d42a96958"

    def install
      bin.install "gituser"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucasnevespereira/go-gituser/releases/download/vv1.5.0/gituser_v1.5.0_linux_arm64.tar.gz"
      sha256 "f6220126614d1ddeb717eef6b81fe7ceea21f37523bde0f56945f96d42a96958"

      def install
        bin.install "gituser"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucasnevespereira/go-gituser/releases/download/vv1.5.0/gituser_v1.5.0_linux_amd64.tar.gz"
      sha256 "f6220126614d1ddeb717eef6b81fe7ceea21f37523bde0f56945f96d42a96958"

      def install
        bin.install "gituser"
      end
    end
  end
end
