# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGituser < Formula
  desc ""
  homepage "https://github.com/lucasnevespereira/homebrew-tools"
  version "1.1.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lucasnevespereira/go-gituser/releases/download/v1.1.9/go-gituser_1.1.9_Darwin_x86_64.tar.gz"
      sha256 "00f6ac5849b426d6a0ae7a548c3171bf4fd91f5f51863d7bb1ee42cefa16651e"

      def install
        bin.install "go-gituser"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lucasnevespereira/go-gituser/releases/download/v1.1.9/go-gituser_1.1.9_Darwin_arm64.tar.gz"
      sha256 "de1407a085cdec6b591df04f37bfb443a395f0d0e4b80410de41a47445b0c11c"

      def install
        bin.install "go-gituser"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucasnevespereira/go-gituser/releases/download/v1.1.9/go-gituser_1.1.9_Linux_arm64.tar.gz"
      sha256 "2afd37286b5b19625814fae09a2b3562acf94d5859e37b626af7b24cf91745f7"

      def install
        bin.install "go-gituser"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucasnevespereira/go-gituser/releases/download/v1.1.9/go-gituser_1.1.9_Linux_x86_64.tar.gz"
      sha256 "9956d25bdfa5b4f1f6c9cd1517ac4790f2ad95d4bb07b9ab88b250bc2c0ae24c"

      def install
        bin.install "go-gituser"
      end
    end
  end
end
