# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lembra < Formula
  desc ""
  homepage "https://github.com/lucasnevespereira/homebrew-tools"
  version "0.0.4"

  on_macos do
    url "https://github.com/lucasnevespereira/lembra/releases/download/v0.0.4/lembra_0.0.4_darwin_all.tar.gz"
    sha256 "6b2418b3614ecef189c7e5af48559d28702398be120f18376a6cf35626944dc9"

    def install
      bin.install "lembra"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucasnevespereira/lembra/releases/download/v0.0.4/lembra_0.0.4_linux_arm64.tar.gz"
      sha256 "d7ffe02fd2c0e47a3d2c5cf8e43ffc55bfaf53396c969b30709adb1026cb9717"

      def install
        bin.install "lembra"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucasnevespereira/lembra/releases/download/v0.0.4/lembra_0.0.4_linux_amd64.tar.gz"
      sha256 "7d8992f6e10342b49b12068059ca72aa77ffb9959c53329858bd4a0295b41e89"

      def install
        bin.install "lembra"
      end
    end
  end
end
