# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lembra < Formula
  desc ""
  homepage "https://github.com/lucasnevespereira/homebrew-tools"
  version "0.0.1"

  on_macos do
    url "https://github.com/lucasnevespereira/lembra/releases/download/v0.0.1/lembra_0.0.1_darwin_all.tar.gz"
    sha256 "f07fe6808ffb84012c699a1ded4e0ccb065ff7fba8592d7f33b8f873a4fd1d22"

    def install
      bin.install "lembra"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucasnevespereira/lembra/releases/download/v0.0.1/lembra_0.0.1_linux_arm64.tar.gz"
      sha256 "87e3badd691d736a720aaf480081ae85320a56bc1ad0c97387c30cb9f141f318"

      def install
        bin.install "lembra"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucasnevespereira/lembra/releases/download/v0.0.1/lembra_0.0.1_linux_amd64.tar.gz"
      sha256 "78352b2e5928eee4a7a5c7f5a287bee1d7e33897867a533851d508d5eaba672d"

      def install
        bin.install "lembra"
      end
    end
  end
end
