# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lembra < Formula
  desc ""
  homepage "https://github.com/lucasnevespereira/homebrew-tools"
  version "0.0.2"

  on_macos do
    url "https://github.com/lucasnevespereira/lembra/releases/download/v0.0.2/lembra_0.0.2_darwin_all.tar.gz"
    sha256 "3e1c4818d4657bd5061fd3024310a60c4213e0e1dac6bbcbd6023bed22ec62dd"

    def install
      bin.install "lembra"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucasnevespereira/lembra/releases/download/v0.0.2/lembra_0.0.2_linux_arm64.tar.gz"
      sha256 "f8c6576119ba15e25a4394d47366a8be6123740aa3b2cd5839766e649f3e5063"

      def install
        bin.install "lembra"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucasnevespereira/lembra/releases/download/v0.0.2/lembra_0.0.2_linux_amd64.tar.gz"
      sha256 "ea703e2ea1bfed1f41df6e295cdc0c65dd6b43fc5f5f6ba31bc9af4bb57f65be"

      def install
        bin.install "lembra"
      end
    end
  end
end
