# This file was generated by GoReleaser. DO NOT EDIT.
cask "gituser" do
  desc ""
  homepage ""
  version "1.5.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gituser"

  on_macos do
    url "https://github.com/lucasnevespereira/go-gituser/releases/download/v1.5.3/gituser_1.5.3_darwin_all.tar.gz",
        verified: "github.com/lucanevespereira/go-gituser",
        using: :homebrew_curl
    sha256 "cd6f1c8c3baa396645b8e7c987896f0daeda34066168249fc5e7f8f88595b114"
  end

  on_linux do
    on_intel do
      url "https://github.com/lucasnevespereira/go-gituser/releases/download/v1.5.3/gituser_1.5.3_linux_amd64.tar.gz",
        verified: "github.com/lucanevespereira/go-gituser",
        using: :homebrew_curl
      sha256 "27ff355052570c7d1b596cf8f3e46963afb5c1300023137d2c8ed78cdbf2138e"
    end
    on_arm do
      url "https://github.com/lucasnevespereira/go-gituser/releases/download/v1.5.3/gituser_1.5.3_linux_arm64.tar.gz",
        verified: "github.com/lucanevespereira/go-gituser",
        using: :homebrew_curl
      sha256 "fd63cda981496a54d18e5832ccecf02222369e0175f7aae3bff0153e6b859f55"
    end
  end

  conflicts_with formula: [
      "gituser",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gituser"]
    end
  end

  # No zap stanza required
end
