# This file was generated by GoReleaser. DO NOT EDIT.
cask "gituser" do
  desc ""
  homepage ""
  version "1.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gituser"

  on_macos do
    url "https://github.com/lucasnevespereira/go-gituser/releases/download/v1.5.0/gituser_1.5.0_darwin_all.tar.gz",
        verified: "github.com/lucanevespereira/go-gituser",
        using: :homebrew_curl
    sha256 "250256ab5d03efc7896ef4b4352d5325039cc6d419364a3a83af0712dd002b4f"
  end

  on_linux do
    on_intel do
      url "https://github.com/lucasnevespereira/go-gituser/releases/download/v1.5.0/gituser_1.5.0_linux_amd64.tar.gz",
        verified: "github.com/lucanevespereira/go-gituser",
        using: :homebrew_curl
      sha256 "a6d46324f7fc0a71eaba0e38ded2e47080f064d3358c90548ff6d47e2fe120b8"
    end
    on_arm do
      url "https://github.com/lucasnevespereira/go-gituser/releases/download/v1.5.0/gituser_1.5.0_linux_arm64.tar.gz",
        verified: "github.com/lucanevespereira/go-gituser",
        using: :homebrew_curl
      sha256 "4dd3fde3a004717e434f9f6fa0c85c86c4727c53e771d91289fb2c45fe319ac1"
    end
  end

  conflicts_with formula: [
      "gituser",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gituser"]
    end
  end

  # No zap stanza required
end
