# This file was generated by GoReleaser. DO NOT EDIT.
cask "gituser" do
  desc ""
  homepage ""
  version "1.5.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gituser"

  on_macos do
    url "https://github.com/lucasnevespereira/go-gituser/releases/download/v1.5.2/gituser_1.5.2_darwin_all.tar.gz",
        verified: "github.com/lucanevespereira/go-gituser",
        using: :homebrew_curl
    sha256 "d9e6130b44f0f6d81fd43047cf01318af5b2ed460488b1209fbe4fb579b35bdf"
  end

  on_linux do
    on_intel do
      url "https://github.com/lucasnevespereira/go-gituser/releases/download/v1.5.2/gituser_1.5.2_linux_amd64.tar.gz",
        verified: "github.com/lucanevespereira/go-gituser",
        using: :homebrew_curl
      sha256 "eddcde7ce04ac93556f8b50b75538c93ee8eafed2c3653dd350ea556abafa3c7"
    end
    on_arm do
      url "https://github.com/lucasnevespereira/go-gituser/releases/download/v1.5.2/gituser_1.5.2_linux_arm64.tar.gz",
        verified: "github.com/lucanevespereira/go-gituser",
        using: :homebrew_curl
      sha256 "cc03b5c41f2eedcb7c55234a14d762cba694b2dfe7a4a0b60327cc95824d3853"
    end
  end

  conflicts_with formula: [
      "gituser",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gituser"]
    end
  end

  # No zap stanza required
end
